// Code generated by mockery v2.8.0. DO NOT EDIT.

package mock

import (
	context "context"

	model "github.com/MuZaZaVr/account-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Company is an autogenerated mock type for the Company type
type Company struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, company
func (_m *Company) Create(ctx context.Context, company model.CompanyDTO) (string, error) {
	ret := _m.Called(ctx, company)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, model.CompanyDTO) string); ok {
		r0 = rf(ctx, company)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.CompanyDTO) error); ok {
		r1 = rf(ctx, company)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Company) Delete(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *Company) FindByName(ctx context.Context, name string) (*model.CompanyDTO, error) {
	ret := _m.Called(ctx, name)

	var r0 *model.CompanyDTO
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.CompanyDTO); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CompanyDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByURL provides a mock function with given fields: ctx, url
func (_m *Company) FindByURL(ctx context.Context, url string) (*model.CompanyDTO, error) {
	ret := _m.Called(ctx, url)

	var r0 *model.CompanyDTO
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.CompanyDTO); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CompanyDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsExist provides a mock function with given fields: ctx, name
func (_m *Company) IsExist(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDescription provides a mock function with given fields: ctx, id, newDescription
func (_m *Company) UpdateDescription(ctx context.Context, id string, newDescription string) (string, error) {
	ret := _m.Called(ctx, id, newDescription)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, id, newDescription)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, newDescription)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateName provides a mock function with given fields: ctx, id, newName
func (_m *Company) UpdateName(ctx context.Context, id string, newName string) (string, error) {
	ret := _m.Called(ctx, id, newName)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, id, newName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, newName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateURL provides a mock function with given fields: ctx, id, newUrl
func (_m *Company) UpdateURL(ctx context.Context, id string, newUrl string) (string, error) {
	ret := _m.Called(ctx, id, newUrl)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, id, newUrl)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, newUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
